# Generated by Django 6.1 on 2026-08-26 21:21

import apps_core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        ('apps_livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cni', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('VELO', 'Vélo'), ('MOTO', 'Moto'), ('TRICYCLE', 'Tricycle motorisé'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion (gros volume)')], max_length=15)),
                ('immatriculation', models.CharField(blank=True, max_length=20)),
                ('capacite_charge_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacité de charge (kg)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif / Disponible'), ('EN_MISSION', 'En mission'), ('PAUSE', 'En pause'), ('INACTIF', 'Inactif / Hors ligne'), ('SUSPENDU', 'Suspendu')], default='INACTIF', max_length=15)),
                ('latitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('derniere_position', models.DateTimeField(blank=True, null=True)),
                ('total_livraisons', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('photo_cni', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL)),
                ('zones_travail', models.ManyToManyField(blank=True, related_name='livreurs', to='apps_core.zone')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['utilisateur__nom'],
            },
        ),
        migrations.CreateModel(
            name='PositionLivreurHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('livraison_en_cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_position', to='apps_livraison.livraison')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_positions', to='apps_livreur.livreur')),
            ],
            options={
                'verbose_name': 'Position livreur (historique)',
                'verbose_name_plural': 'Positions livreurs (historique)',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['livreur', 'horodatage'], name='apps_livreu_livreur_07fbc3_idx')],
            },
        ),
    ]
