# Generated by Django 6.1 on 2026-08-26 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('SMS', "SMS (Africa's Talking)"), ('WHATSAPP', 'WhatsApp Business API'), ('EMAIL', 'Email'), ('PUSH', 'Push mobile (FCM)')], max_length=10)),
                ('evenement', models.CharField(choices=[('LIV_CREEE', 'Livraison créée'), ('LIV_VALIDEE', 'Livraison validée'), ('LIV_REFUSEE', 'Livraison refusée'), ('LIV_EN_COURS', 'Livraison en cours'), ('LIV_LIVREE', 'Livraison effectuée'), ('LIV_ECHEC', 'Échec livraison'), ('RECEP_VALID', "Réception à valider par l'entreprise"), ('RECAP_GAIN', 'Récapitulatif gain livraison'), ('LOT_ENVOYE', 'Lot de paiement envoyé (preuve jointe)'), ('ENT_VALIDEE', 'Entreprise validée'), ('ENT_REFUSEE', 'Entreprise refusée'), ('ENT_INACTIF', 'Entreprise désactivée pour inactivité'), ('PROD_VALIDE', 'Produit validé'), ('STOCK_BAS', 'Alerte stock bas'), ('BONUS', 'Bonus attribué')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('statut_envoi', models.CharField(choices=[('EN_ATTENTE', "En file d'attente"), ('ENVOYE', 'Envoyé'), ('LIVRE', 'Livré (accusé réception)'), ('ECHEC', "Échec d'envoi")], default='EN_ATTENTE', max_length=15)),
                ('ref_externe', models.CharField(blank=True, max_length=100)),
                ('erreur', models.TextField(blank=True)),
                ('nb_tentatives', models.PositiveSmallIntegerField(default=0)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_notif', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='apps_livraison.livraison')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['statut_envoi', 'canal'], name='apps_notifi_statut__4f346f_idx'), models.Index(fields=['destinataire', 'date_envoi'], name='apps_notifi_destina_84a3fb_idx')],
            },
        ),
    ]
