# Generated by Django 6.1 on 2026-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='evenement',
            field=models.CharField(choices=[('OTP_ENVOYE', 'Code OTP envoyé'), ('MDP_REINIT', 'Réinitialisation mot de passe demandée'), ('LIV_CREEE', 'Livraison créée'), ('LIV_VALIDEE', 'Livraison validée'), ('LIV_REFUSEE', 'Livraison refusée'), ('LIV_EN_COURS', 'Livraison en cours'), ('LIV_LIVREE', 'Livraison effectuée'), ('LIV_ECHEC', 'Échec livraison'), ('RECEP_VALID', "Réception à valider par l'entreprise"), ('RECAP_GAIN', 'Récapitulatif gain livraison'), ('LOT_ENVOYE', 'Lot de paiement envoyé (preuve jointe)'), ('ENT_VALIDEE', 'Entreprise validée'), ('ENT_REFUSEE', 'Entreprise refusée'), ('ENT_INACTIF', 'Entreprise désactivée pour inactivité'), ('PROD_VALIDE', 'Produit validé'), ('STOCK_BAS', 'Alerte stock bas'), ('BONUS', 'Bonus attribué')], max_length=20),
        ),
    ]
