# Generated by Django 6.1 on 2026-08-26 21:21

import apps_core.validators
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('BAS', 'Stock bas (seuil alerte atteint)'), ('RUPTURE', 'Rupture de stock')], max_length=10)),
                ('quantite_au_moment', models.PositiveIntegerField()),
                ('traitee', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerte stock',
                'verbose_name_plural': 'Alertes stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icone', models.CharField(blank=True, max_length=60)),
                ('couleur', models.CharField(blank=True, max_length=7)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('ENTREE_INIT', 'Entrée initiale (enregistrement)'), ('ENTREE_REAPP', 'Réapprovisionnement'), ('TRANSFERT', 'Transfert entre entrepôts'), ('SORTIE_LIV', 'Sortie pour livraison'), ('RETOUR_LIV', 'Retour de livraison (échec)'), ('RETOUR_PROP', 'Retour au propriétaire (inactivité)'), ('AJUST_PLUS', 'Ajustement positif (inventaire)'), ('AJUST_MOINS', 'Ajustement négatif (inventaire)'), ('PERTE', 'Perte / Casse / Vol'), ('PEREMPTION', 'Péremption / Retrait')], db_index=True, max_length=20)),
                ('quantite', models.IntegerField(help_text='Positif = entrée, Négatif = sortie')),
                ('stock_avant', models.PositiveIntegerField()),
                ('stock_apres', models.PositiveIntegerField()),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=apps_core.validators.upload_path)),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Photo produit',
                'verbose_name_plural': 'Photos produits',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('reference_sku', models.CharField(blank=True, max_length=60)),
                ('code_barre', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unite', models.CharField(choices=[('PIECE', 'Pièce(s)'), ('KG', 'Kilogramme(s)'), ('GRAMME', 'Gramme(s)'), ('LITRE', 'Litre(s)'), ('ML', 'Millilitre(s)'), ('CARTON', 'Carton(s)'), ('SACHET', 'Sachet(s)'), ('BOUTEILLE', 'Bouteille(s)'), ('BOITE', 'Boîte(s)'), ('PALETTE', 'Palette(s)'), ('METRE', 'Mètre(s)')], default='PIECE', max_length=15)),
                ('seuil_alerte_defaut', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte par défaut (par entrepôt)")),
                ('seuil_rupture_defaut', models.PositiveIntegerField(default=0, verbose_name='Seuil de rupture par défaut (par entrepôt)')),
                ('vendu_en_ligne', models.BooleanField(default=False, help_text='Cocher UNIQUEMENT si Yopishop gère la livraison de ce produit. Sinon, même si l\'entreprise vend par ailleurs en ligne, le produit reste "hors-ligne" pour le calcul des frais.', verbose_name='Vendu en ligne (Yopishop gère la vente ET la livraison)')),
                ('reference_yopishop', models.CharField(blank=True, help_text='ID/SKU utilisé pour la synchronisation avec Yopishop', max_length=100, verbose_name='Référence produit Yopishop')),
                ('qualite_produit', models.CharField(choices=[('LEGER', 'Léger (moto compatible)'), ('LOURD', 'Lourd / volumineux (véhicule requis)'), ('MIXTE', 'Mixte (dépend du produit précis)')], default='LEGER', help_text='LEGER = transportable en moto ; LOURD = véhicule requis', max_length=10, verbose_name='Qualité du produit')),
                ('vehicule_minimum_requis', models.CharField(choices=[('VELO', 'Vélo'), ('MOTO', 'Moto'), ('TRICYCLE', 'Tricycle motorisé'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion (gros volume)')], default='MOTO', help_text='Utilisé pour calculer la majoration des frais de livraison', max_length=15, verbose_name='Véhicule minimum requis')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('longueur_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('largeur_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hauteur_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fragile', models.BooleanField(default=False)),
                ('necessite_froid', models.BooleanField(default=False)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation entreprise'), ('VALIDE', 'Validé'), ('REFUSE', "Refusé par l'entreprise"), ('EPUISE', 'Stock épuisé (tous entrepôts)'), ('ARCHIVE', 'Archivé')], db_index=True, default='EN_ATTENTE', max_length=15)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['entreprise', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RetourStockProprietaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_retournee', models.PositiveIntegerField()),
                ('motif', models.CharField(choices=[('INACTIVITE', 'Inactivité 30 jours'), ('DEMANDE', "Demande de l'entreprise"), ('FERMETURE', "Fermeture de l'entrepôt")], max_length=15)),
                ('confirme_retire_par_entreprise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Retour de stock au propriétaire',
                'verbose_name_plural': 'Retours de stock aux propriétaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StockEntrepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('quantite_reservee', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('seuil_rupture', models.PositiveIntegerField(default=0)),
                ('emplacement_precis', models.CharField(blank=True, max_length=50, verbose_name='Emplacement (allée/rayon)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock par entrepôt',
                'verbose_name_plural': 'Stocks par entrepôt',
            },
        ),
    ]
