# Generated by Django 6.1 on 2026-08-26 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_catalogue', '0002_initial'),
        ('apps_entreprise', '0001_initial'),
        ('apps_livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='apps_livraison.livraison'),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='apps_catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='enregistre_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='apps_entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='produit',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apps_catalogue.produit'),
        ),
        migrations.AddField(
            model_name='retourstockproprietaire',
            name='entrepot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_entreprise.entrepot'),
        ),
        migrations.AddField(
            model_name='retourstockproprietaire',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours_stock', to='apps_entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='retourstockproprietaire',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours_stock', to='apps_catalogue.produit'),
        ),
        migrations.AddField(
            model_name='stockentrepot',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_produits', to='apps_entreprise.entrepot'),
        ),
        migrations.AddField(
            model_name='stockentrepot',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_entrepots', to='apps_catalogue.produit'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='stock_entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='apps_catalogue.stockentrepot'),
        ),
        migrations.AddField(
            model_name='alertestock',
            name='stock_entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='apps_catalogue.stockentrepot'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['statut', 'entreprise'], name='apps_catalo_statut_3b558e_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['vendu_en_ligne', 'statut'], name='apps_catalo_vendu_e_0e2f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['reference_sku'], name='apps_catalo_referen_d87e49_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentrepot',
            index=models.Index(fields=['entrepot', 'produit'], name='apps_catalo_entrepo_9872ff_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentrepot',
            index=models.Index(fields=['quantite_stock', 'seuil_alerte'], name='apps_catalo_quantit_611b7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockentrepot',
            unique_together={('produit', 'entrepot')},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['stock_entrepot', 'date'], name='apps_catalo_stock_e_b10df8_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement', 'date'], name='apps_catalo_type_mo_d90331_idx'),
        ),
    ]
