# Generated by Django 6.1 on 2026-08-26 21:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_entreprise', '0001_initial'),
        ('apps_livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_conv', models.CharField(choices=[('ADMIN_ADMIN', 'Admin - Admin'), ('ADMIN_ENT', 'Admin - Entreprise'), ('ADMIN_LIV', 'Admin - Livreur'), ('ADMIN_CLI', 'Admin - Client')], db_index=True, max_length=15)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('est_archivee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_dernier_msg', models.DateTimeField(db_index=True, null=True)),
                ('entreprise_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='apps_entreprise.entreprise')),
                ('livraison_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='apps_livraison.livraison')),
                ('participant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en_tant_que_1', to=settings.AUTH_USER_MODEL)),
                ('participant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_en_tant_que_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-date_dernier_msg'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('type_contenu', models.CharField(choices=[('TEXTE', 'Texte'), ('FICHIER', 'Fichier joint'), ('SYSTEME', 'Message système')], default='TEXTE', max_length=10)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='message/fichier/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'doc', 'docx', 'xlsx'])])),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apps_messagerie.conversation')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_envoye', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_1', 'est_archivee'], name='apps_messag_partici_4914ec_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_2', 'est_archivee'], name='apps_messag_partici_5623b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant_1', 'participant_2')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'date_envoi'], name='apps_messag_convers_b19b50_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'lu'], name='apps_messag_expedit_fc5e6b_idx'),
        ),
    ]
