# Generated by Django 6.1 on 2026-08-26 21:21

import apps_core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_bonus', '0002_initial'),
        ('apps_catalogue', '0002_initial'),
        ('apps_entreprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivraisonDirecte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=25, unique=True)),
                ('nom_expediteur', models.CharField(max_length=150)),
                ('telephone_expediteur', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('description_colis', models.TextField()),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valeur_declaree', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('adresse_collecte', models.TextField()),
                ('latitude_depart', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_depart', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('nom_destinataire', models.CharField(max_length=150)),
                ('telephone_destinataire', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('adresse_livraison', models.TextField()),
                ('latitude_arrivee', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_arrivee', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('type_tarification', models.CharField(choices=[('INTRA_ZONE', 'Intra-zone (tarif zone)'), ('INTER_VILLE', 'Inter-villes (table de tarifs)'), ('AU_KM', 'Calcul au kilomètre'), ('NEGOCIE', 'Prix négocié avec le client')], default='AU_KM', max_length=15)),
                ('vehicule_requis', models.CharField(choices=[('VELO', 'Vélo'), ('MOTO', 'Moto'), ('TRICYCLE', 'Tricycle motorisé'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion (gros volume)')], default='MOTO', max_length=15)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tarif_par_km', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8)),
                ('prix_negocie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de confirmation'), ('CONFIRMEE', 'Confirmée'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('ECHEC', 'Échec'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=15)),
                ('token_suivi', models.CharField(blank=True, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livraison directe',
                'verbose_name_plural': 'Livraisons directes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut_avant', models.CharField(blank=True, max_length=15)),
                ('statut_apres', models.CharField(max_length=15)),
                ('commentaire', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique statut livraison',
                'verbose_name_plural': 'Historiques statuts livraisons',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendu_en_ligne_snapshot', models.BooleanField(default=False)),
                ('vehicule_requis_snapshot', models.CharField(choices=[('VELO', 'Vélo'), ('MOTO', 'Moto'), ('TRICYCLE', 'Tricycle motorisé'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion (gros volume)')], default='MOTO', max_length=15)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_livraison', to='apps_catalogue.produit')),
                ('stock_entrepot', models.ForeignKey(help_text="Entrepôt précis d'où le produit est prélevé", on_delete=django.db.models.deletion.PROTECT, related_name='lignes_livraison', to='apps_catalogue.stockentrepot')),
            ],
            options={
                'verbose_name': 'Ligne de livraison',
                'verbose_name_plural': 'Lignes de livraison',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, help_text='Généré auto : SD-YYYYMMDD-XXXX', max_length=25, unique=True)),
                ('origine_commande', models.CharField(choices=[('YOPISHOP', 'Commande en ligne (Yopishop)'), ('ENTREPRISE', "Demande manuelle de l'entreprise")], help_text="YOPISHOP : commande passée en ligne, réceptionnée en 1er par la plateforme. ENTREPRISE : demande envoyée directement par l'entreprise à la plateforme.", max_length=15, verbose_name='Origine de la commande')),
                ('adresse_exacte', models.TextField()),
                ('coordonnees_livraison_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('coordonnees_livraison_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('telephone_client_2', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('priorite', models.CharField(choices=[('NORMALE', 'Normale (24–48h)'), ('URGENTE', 'Urgente (4–8h) +frais'), ('PREMIUM', 'Premium (même jour) +frais')], default='NORMALE', max_length=10)),
                ('mode_encaissement', models.CharField(choices=[('A_LA_LIVRAISON', 'Paiement à la livraison'), ('DEJA_PAYE', 'Déjà payé par le client'), ('VIREMENT', 'Virement / Mobile Money')], default='A_LA_LIVRAISON', max_length=20)),
                ('montant_a_encaisser', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note_livreur', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon (non soumis)'), ('EN_ATTENTE', 'En attente de validation admin'), ('VALIDEE', 'Validée par admin'), ('REFUSEE', 'Refusée par admin'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée avec succès ✅'), ('ECHEC', 'Échec de livraison ❌'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=15)),
                ('motif_refus', models.TextField(blank=True)),
                ('motif_echec', models.TextField(blank=True)),
                ('statut_reception', models.CharField(choices=[('ATTENTE_LIV', 'En attente de livraison au client'), ('INFOS_ENVOYEES', "Livrée — infos envoyées à l'entreprise"), ('VALIDEE', "Réception validée par l'entreprise"), ('PAIEMENT_ATTENTE', 'En attente du paiement du lot'), ('PAIEMENT_RECU', 'Paiement reçu et confirmé')], default='ATTENTE_LIV', help_text="YOPISHOP : la plateforme réceptionne/traite la commande, l'entreprise valide juste la réception après livraison. ENTREPRISE : l'entreprise suit chaque étape (attribution, en cours, livrée) puis valide la réception.", max_length=20, verbose_name='Statut de réception (côté entreprise)')),
                ('date_validation_reception', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('vehicule_requis', models.CharField(choices=[('VELO', 'Vélo'), ('MOTO', 'Moto'), ('TRICYCLE', 'Tricycle motorisé'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion (gros volume)')], default='MOTO', max_length=15, verbose_name='Véhicule minimum requis (auto-calculé)')),
                ('type_facturation', models.CharField(choices=[('GRATUITE_COM', 'Gratuite pour le client (commission Yopishop 10%)'), ('FACTUREE_ZONE', 'Facturée selon la zone / véhicule')], default='FACTUREE_ZONE', max_length=15)),
                ('contient_produit_en_ligne', models.BooleanField(default=False)),
                ('contient_produit_hors_ligne', models.BooleanField(default=False)),
                ('montant_total_produits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frais_livraison_base_zone', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais zone (avant majoration véhicule) FCFA')),
                ('frais_livraison_applique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 si type_facturation = GRATUITE_COMMISSION', max_digits=10, verbose_name='Frais de livraison finaux appliqués (FCFA)')),
                ('commission_yopishop_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage prélevé par la plateforme sur le montant produits (cas 100% en ligne)', max_digits=5)),
                ('commission_yopishop_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frais_livraison_paye_par_client', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant des frais payé par le client (constaté livreur)')),
                ('frais_livraison_paye_integralement', models.BooleanField(default=False)),
                ('date_signalement_frais', models.DateTimeField(blank=True, null=True)),
                ('gain_entreprise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant net dû à l'entreprise après déduction des frais/commission non couverts", max_digits=12)),
                ('reduction_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path)),
                ('signature_client_img', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path)),
                ('code_confirmation', models.CharField(blank=True, max_length=4)),
                ('confirmation_recu', models.BooleanField(default=False)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_attribuees_par', to=settings.AUTH_USER_MODEL)),
                ('bonus_applique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_concernees', to='apps_bonus.bonusentreprise')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='apps_entreprise.entreprise')),
                ('frais_livraison_signale_par', models.ForeignKey(blank=True, help_text='Le livreur qui a constaté le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_livraison_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livraison B2B',
                'verbose_name_plural': 'Livraisons B2B',
                'ordering': ['-date_creation'],
            },
        ),
    ]
