# Generated by Django 6.1 on 2026-08-26 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        ('apps_entreprise', '0001_initial'),
        ('apps_livraison', '0001_initial'),
        ('apps_livreur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_attribuees', to='apps_livreur.livreur'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='quartier_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='apps_core.quartier'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='valide_reception_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_reception_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='ville_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps_core.ville'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='zone_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='apps_core.zone'),
        ),
        migrations.AddField(
            model_name='lignelivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='apps_livraison.livraison'),
        ),
        migrations.AddField(
            model_name='historiquestatutlivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='apps_livraison.livraison'),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_directes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='livraison_par_entreprise',
            field=models.ForeignKey(blank=True, help_text="Renseigné si une entreprise inscrite est à l'origine de cette livraison directe", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_directes_initiees', to='apps_entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_directes', to='apps_livreur.livreur'),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='ville_collecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departs_directs', to='apps_core.ville'),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='ville_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivees_directes', to='apps_core.ville'),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='zone_collecte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departs_directs', to='apps_core.zone'),
        ),
        migrations.AddField(
            model_name='livraisondirecte',
            name='zone_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivees_directes', to='apps_core.zone'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['statut', 'entreprise'], name='apps_livrai_statut_1cc6af_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['numero'], name='apps_livrai_numero_b3a6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['statut', 'date_creation'], name='apps_livrai_statut_e7a661_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['livreur', 'statut'], name='apps_livrai_livreur_63a231_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['origine_commande', 'statut_reception'], name='apps_livrai_origine_3e5c6d_idx'),
        ),
    ]
