# Generated by Django 6.1 on 2026-08-26 21:21

import apps_core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('VELO', 'Vélo'), ('MOTO', 'Moto'), ('TRICYCLE', 'Tricycle motorisé'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion (gros volume)')], max_length=15, unique=True, verbose_name='Type de véhicule')),
                ('coefficient_multiplicateur', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Ex: 1.00 = moto (référence), 1.50 = voiture (+50%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Coefficient multiplicateur')),
                ('frais_fixe_supplement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant fixe ajouté après application du coefficient', max_digits=10, verbose_name='Supplément fixe (FCFA)')),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coefficient véhicule',
                'verbose_name_plural': 'Coefficients véhicules',
                'ordering': ['coefficient_multiplicateur'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code_iso', models.CharField(max_length=2, unique=True, verbose_name='Code ISO 3166-1 alpha-2')),
                ('indicatif', models.CharField(max_length=6, verbose_name='Indicatif téléphonique')),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('ENTREPRISE', 'Entreprise'), ('LIVREUR', 'Livreur'), ('CLIENT', 'Client Direct')], db_index=True, default='CLIENT', max_length=20, verbose_name='Rôle')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path, verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, verbose_name='Bio / Description')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue préférée')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('email_verifie', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('telephone_verifie', models.BooleanField(default=False, verbose_name='Téléphone vérifié (OTP)')),
                ('code_otp', models.CharField(blank=True, max_length=6, verbose_name='Code OTP en cours')),
                ('code_otp_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP')),
                ('token_reinit_mdp', models.CharField(blank=True, max_length=64, verbose_name='Token réinitialisation MDP')),
                ('token_reinit_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration token MDP')),
                ('tentatives_connexion', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives échouées')),
                ('compte_bloque_jusqu_au', models.DateTimeField(blank=True, null=True, verbose_name="Compte bloqué jusqu'au")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('derniere_connexion_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP dernière connexion')),
                ('device_token', models.CharField(blank=True, help_text='FCM token pour les notifications push', max_length=255, verbose_name='Token appareil mobile (push)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(verbose_name='Valeur')),
                ('type_valeur', models.CharField(choices=[('str', 'Texte'), ('int', 'Entier'), ('float', 'Décimal'), ('bool', 'Booléen'), ('json', 'JSON')], default='str', max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('code', models.CharField(help_text='Ex: DLA pour Douala', max_length=10, unique=True, verbose_name='Code ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Ville active')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='apps_core.pays')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['pays', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifInterVille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_forfaitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Si renseigné, prioritaire sur le calcul au km', max_digits=10, null=True, verbose_name='Prix forfaitaire (FCFA)')),
                ('tarif_par_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarif au km (FCFA)')),
                ('distance_km_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance de référence (km)')),
                ('coefficient_vehicule_applicable', models.BooleanField(default=True, verbose_name='Appliquer aussi la majoration véhicule')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ville_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_arrivee', to='apps_core.ville')),
                ('ville_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_depart', to='apps_core.ville')),
            ],
            options={
                'verbose_name': 'Tarif inter-villes',
                'verbose_name_plural': 'Tarifs inter-villes',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_livraison', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix livraison de référence — véhicule MOTO (FCFA)')),
                ('prix_dynamique', models.BooleanField(default=False, verbose_name='Tarification dynamique (heure pointe)')),
                ('coefficient_pointe', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('3.00'))], verbose_name='Coefficient heure de pointe')),
                ('heure_pointe_debut', models.TimeField(blank=True, null=True)),
                ('heure_pointe_fin', models.TimeField(blank=True, null=True)),
                ('latitude_centre', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_centre', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rayon_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Zone active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='apps_core.ville')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raison', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_tarifs', to='apps_core.zone')),
            ],
            options={
                'verbose_name': 'Historique tarif',
                'verbose_name_plural': 'Historiques tarifs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('repere', models.CharField(blank=True, max_length=200, verbose_name='Point de repère connu')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='apps_core.zone')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['zone', 'nom'],
            },
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email', 'role'], name='apps_core_u_email_efefc4_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role', 'est_actif'], name='apps_core_u_role_449127_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ville',
            unique_together={('pays', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='tarifinterville',
            unique_together={('ville_depart', 'ville_arrivee')},
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['ville', 'est_active'], name='apps_core_z_ville_i_110bc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('ville', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='quartier',
            unique_together={('zone', 'nom')},
        ),
    ]
