# Generated by Django 6.1 on 2026-08-26 21:21

import apps_core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'entrepôt")),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Code entrepôt')),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('capacite_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacité (m³)')),
                ('gere_produits_froid', models.BooleanField(default=False, verbose_name="Dispose d'une chambre froide")),
                ('gere_produits_lourds', models.BooleanField(default=False, verbose_name='Adapté aux produits lourds/volumineux')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, help_text="Admin/agent responsable de l'entrepôt", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots_geres', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrepots', to='apps_core.ville')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots', to='apps_core.zone')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AffectationEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('affecte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_entrepot_realisees', to=settings.AUTH_USER_MODEL)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_entreprise.entrepot')),
            ],
            options={
                'verbose_name': 'Affectation entrepôt',
                'verbose_name_plural': 'Affectations entrepôts',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('nom_commercial', models.CharField(blank=True, max_length=200, verbose_name='Nom commercial')),
                ('secteur', models.CharField(choices=[('COMMERCE', 'Commerce / Distribution'), ('RESTAURATION', 'Restauration / Food'), ('PHARMACIE', 'Pharmaceutique / Santé'), ('ELECTRONIQUE', 'Électronique / High-Tech'), ('MODE', 'Mode / Textile'), ('COSMETIQUE', 'Cosmétique / Beauté'), ('AGRICULTURE', 'Agriculture / Agro-alimentaire'), ('IMPRIMERIE', 'Imprimerie / Papeterie'), ('BATIMENT', 'Bâtiment / Matériaux'), ('INFORMATIQUE', 'Informatique / Téléphonie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('taille', models.CharField(choices=[('MICRO', 'Micro (1–5 employés)'), ('PETITE', 'Petite (6–20 employés)'), ('MOYENNE', 'Moyenne (21–100 employés)'), ('GRANDE', 'Grande (100+ employés)')], default='MICRO', max_length=10)),
                ('type_entreprise', models.CharField(choices=[('VENDEUR_LIGNE', 'Vendeur en ligne uniquement (Yopishop)'), ('VENDEUR_PHYS', 'Vendeur physique uniquement (hors-ligne)'), ('MIXTE', 'Mixte (en ligne + hors-ligne)')], default='VENDEUR_PHYS', help_text="Détermine si l'entreprise vend via Yopishop, en physique, ou les deux", max_length=15, verbose_name="Type d'entreprise")),
                ('qualite_produits_defaut', models.CharField(choices=[('LEGER', 'Léger (moto compatible)'), ('LOURD', 'Lourd / volumineux (véhicule requis)'), ('MIXTE', 'Mixte (dépend du produit précis)')], default='LEGER', help_text="Valeur pré-remplie à la création d'un produit ; modifiable par produit", max_length=10, verbose_name='Qualité produits par défaut')),
                ('numero_registre', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Registre de Commerce')),
                ('numero_contribuable_niu', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='NIU invalide. Lettres majuscules et chiffres uniquement.', regex='^[A-Z0-9]{8,20}$')], verbose_name='N° Contribuable / NIU')),
                ('adresse_siege', models.TextField(verbose_name='Adresse du siège social')),
                ('telephone_principal', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('telephone_whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('email_professionnel', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path)),
                ('couleur_principale', models.CharField(blank=True, max_length=7)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validée'), ('REFUSE', 'Refusée'), ('SUSPENDU', 'Suspendue (décision admin)'), ('DESACTIVE_INACT', 'Désactivée pour inactivité (30j)')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('note_interne_admin', models.TextField(blank=True)),
                ('score_fiabilite', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Score de fiabilité (0–100)')),
                ('notification_sms', models.BooleanField(default=True)),
                ('notification_whatsapp', models.BooleanField(default=True)),
                ('notification_email', models.BooleanField(default=False)),
                ('cycle_paiement', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel')], default='HEBDOMADAIRE', max_length=15, verbose_name='Cycle de règlement')),
                ('numero_paiement_principal', models.CharField(blank=True, max_length=30, verbose_name='Numéro Mobile Money / compte principal')),
                ('derniere_activite_livraison', models.DateTimeField(blank=True, help_text='Mis à jour à chaque nouvelle livraison créée/livrée. Sert au calcul des 30j.', null=True, verbose_name='Dernière activité de livraison')),
                ('date_desactivation_inactivite', models.DateTimeField(blank=True, null=True)),
                ('produits_retournes_proprietaire', models.BooleanField(default=False, verbose_name='Produits déjà retournés au propriétaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises_validees', to=settings.AUTH_USER_MODEL)),
                ('ville_principale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='apps_core.ville')),
                ('zone_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='apps_core.zone')),
                ('zones_favorites', models.ManyToManyField(blank=True, related_name='entreprises_favorites', to='apps_core.zone')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='entrepot',
            name='entreprises',
            field=models.ManyToManyField(blank=True, help_text='Entreprises autorisées à stocker dans cet entrepôt (assignation plateforme)', related_name='entrepots', through='apps_entreprise.AffectationEntrepot', to='apps_entreprise.entreprise'),
        ),
        migrations.CreateModel(
            name='DocumentEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_doc', models.CharField(choices=[('REGISTRE', 'Registre de Commerce'), ('NIU', 'Carte Contribuable / NIU'), ('PLAN', 'Plan de localisation'), ('STATUTS', 'Statuts de la société'), ('DOMICILE', 'Attestation de domicile'), ('CNI', 'CNI du Gérant'), ('AUTRE', 'Autre document')], max_length=20)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to=apps_core.validators.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('taille_fichier', models.PositiveIntegerField(default=0)),
                ('verifie', models.BooleanField(default=False)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verifies', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps_entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Document entreprise',
                'verbose_name_plural': 'Documents entreprises',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='ContactEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_contact', models.CharField(choices=[('GERANT', 'Gérant / Propriétaire'), ('RESPONSABLE', 'Responsable Livraison'), ('COMPTABLE', 'Comptable'), ('COMMERCIAL', 'Commercial'), ('AUTRE', 'Autre')], max_length=15)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +237XXXXXXXXX', regex='^\\+?[0-9]{8,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_principal', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='apps_entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Contact entreprise',
                'verbose_name_plural': 'Contacts entreprises',
                'ordering': ['-est_principal', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='affectationentrepot',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_entreprise.entreprise'),
        ),
        migrations.CreateModel(
            name='FraisGardiennage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paye', models.BooleanField(default=False)),
                ('raison', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_gardiennage', to='apps_entreprise.entreprise')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frais de gardiennage',
                'verbose_name_plural': 'Frais de gardiennage',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['statut', 'date_creation'], name='apps_entrep_statut_05d858_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['secteur', 'statut'], name='apps_entrep_secteur_aebc61_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['score_fiabilite'], name='apps_entrep_score_f_4271ad_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['derniere_activite_livraison'], name='apps_entrep_dernier_832e96_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepot',
            index=models.Index(fields=['ville', 'est_actif'], name='apps_entrep_ville_i_066cac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationentrepot',
            unique_together={('entreprise', 'entrepot')},
        ),
    ]
