# Generated by Django 6.1 on 2026-08-26 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('UTILISE', 'Entièrement utilisé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_expiration', models.DateField()),
                ('nb_utilisations_max', models.PositiveIntegerField(default=0)),
                ('nb_utilisations_actuelles', models.PositiveIntegerField(default=0)),
                ('note_interne', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bonus entreprise',
                'verbose_name_plural': 'Bonus entreprises',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypeBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('RED_ZONE', 'Réduction frais zone (montant fixe)'), ('RED_PCT', 'Réduction frais zone (pourcentage)'), ('PRIORITE', 'Priorité de traitement'), ('LIV_OFFT', 'N livraisons offertes'), ('STOCK_PRE', 'Avantage stockage premium')], max_length=20)),
                ('description', models.TextField()),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de bonus',
                'verbose_name_plural': 'Types de bonus',
            },
        ),
    ]
