# Generated by Django 6.1 on 2026-08-26 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_bonus', '0001_initial'),
        ('apps_core', '0001_initial'),
        ('apps_entreprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusentreprise',
            name='attribue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_attribues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonusentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='apps_entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='bonusentreprise',
            name='zone_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_core.zone'),
        ),
        migrations.AddField(
            model_name='bonusentreprise',
            name='type_bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps_bonus.typebonus'),
        ),
        migrations.AddIndex(
            model_name='bonusentreprise',
            index=models.Index(fields=['entreprise', 'statut'], name='apps_bonus__entrepr_0fcf16_idx'),
        ),
    ]
