# Generated by Django 6.1 on 2026-08-26 21:21

import apps_core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_entreprise', '0001_initial'),
        ('apps_livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPaiementEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('montant_brut_produits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_frais_livraison_deduits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_commission_yopishop_deduite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_net_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('methode_paiement', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Espèces (retrait agence)')], default='MTN_MOMO', max_length=15)),
                ('numero_compte_destination', models.CharField(blank=True, max_length=30)),
                ('reference_transaction_externe', models.CharField(blank=True, max_length=100, verbose_name='Réf. transaction Mobile Money/banque')),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to=apps_core.validators.upload_path)),
                ('statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('PRET', 'Prêt à envoyer'), ('ENVOYE', 'Envoyé (preuve jointe)'), ('CONFIRME', "Confirmé par l'entreprise"), ('LITIGE', 'En litige')], db_index=True, default='PREPARATION', max_length=15)),
                ('note_litige', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation_entreprise', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_paiement_confirmes', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_paiement', to='apps_entreprise.entreprise')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_paiement_envoyes', to=settings.AUTH_USER_MODEL)),
                ('livraisons', models.ManyToManyField(blank=True, related_name='lots_paiement', to='apps_livraison.livraison')),
            ],
            options={
                'verbose_name': 'Lot de paiement entreprise',
                'verbose_name_plural': 'Lots de paiement entreprises',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['entreprise', 'statut'], name='apps_transa_entrepr_2a6fb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_transaction', models.CharField(choices=[('GAIN_ENT', 'Gain entreprise'), ('FRAIS_LIV', 'Frais livraison (plateforme)'), ('COM_YOPI', 'Commission Yopishop (10%)'), ('REMBOURST', 'Remboursement'), ('BONUS', 'Réduction bonus appliquée'), ('FRAIS_DIR', 'Frais livraison directe'), ('GARDIENNAGE', 'Frais de gardiennage (inactivité)')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='apps_entreprise.entreprise')),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='apps_livraison.livraison')),
                ('livraison_directe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='apps_livraison.livraisondirecte')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['entreprise', 'date'], name='apps_transa_entrepr_719bde_idx'), models.Index(fields=['type_transaction', 'statut_paiement'], name='apps_transa_type_tr_072503_idx')],
            },
        ),
    ]
